### ISSUE TITLE
About ecc image encryption

### ISSUE THREAD

**Issue by qimora** [agabhishek/BlockChain-FileChain-Solution#1]
1) I have problem to run the code of ecc image encrypt and decrpyt can you teach me how to run the code 
2) I also have run the code on windows but it does not work 
3) can i know that the image encryption is using ecc algorithm or aes algorithm because i saw the aes algorithm on the code

**Comment by geekygiks** [comment]
You need a linux env to run this. It will not run in windows. ECC algorithm is used for image encryption.

**Comment by qimora** [comment]
Can i know what linux are you using is it kali linux or ubuntu

**Comment by qimora** [comment]
And also can i know the command that you write are run in the terminal or in the python

**Comment by geekygiks** [comment]
Hi.. Ubuntu 16.04 version is used.

Since its a binary/shell script program you can run in terminal..

**Comment by geekygiks** [comment]
You can read up more at https://blockchain-tutorial.com.. Or contact me in the contact us section..
